export type KyfiLocale = "en" | "te";

export const kyfiCopy = {
  en: {
    app: {
      title: "Know Your Farmer Information",
      workspace: "KYFI dealer workspace",
      currentSection: "Current section",
      menu: "Menu",
      selectSection: "Select a section",
      today: "Today",
    },
    common: {
      whatToDoNext: "What to do next",
      whatThisDoes: "What this does",
      rules: "Rules",
      searchResult: "Search result",
      confirmedList: "Confirmed list",
    },
    nav: {
      dashboard: { label: "Dashboard", note: "Overview" },
      search: { label: "Search Farmer Status", note: "Lookup" },
      blacklist: { label: "Blacklist Browser", note: "Warnings" },
      status: { label: "Add Farmer Status", note: "GREEN / YELLOW / RED" },
      addBlacklist: { label: "Add to Blacklist", note: "Critical" },
      records: { label: "My Records", note: "History" },
      profile: { label: "Profile / Settings", note: "Account" },
    },
    dashboard: {
      title: "Home / Dashboard",
      description:
        "This is the main entry screen. Use it to go to Search Farmer Status or View Blacklist.",
      workspaceLabel: "Dealer workspace",
      searchCardTitle: "Search Farmer Status",
      searchCardText: "Search a farmer before giving credit and check the status record.",
      blacklistCardTitle: "View Blacklist",
      blacklistCardText: "Browse confirmed defaulters by mandal and village.",
      nextTitle: "What to do next",
      nextText:
        "Open Search Farmer Status for lookup, or open View Blacklist to browse local warnings.",
      warningTitle: "Blacklist warning",
      warningText: "A BLACKLISTED warning is separate from the status color.",
      warningReady: "View Blacklist ready",
      reasonLabel: "Reason",
      reasonText: "Credit taken and not repaid within the agreed season.",
    },
    search: {
      workspaceLabel: "Farmer search",
      title: "Search by identity or village",
      description: "This is the main dealer action. The interface is meant for fast counter use.",
      primary: "Aadhaar / PAN / Mobile",
      mandal: "Mandal",
      village: "Village",
      enter: "Enter value",
      button: "Search farmer",
      resultTitle: "Rama Devi",
      resultLocation: "Guntur East, Kondapalli",
      blacklisted: "BLACKLISTED",
      warning:
        "A confirmed non-payment warning exists and must be shown before any credit decision.",
      aadhaar: "Aadhaar",
      mobile: "Mobile",
      votes: "Vote count",
      date: "Date added",
    },
    blacklist: {
      workspaceLabel: "Blacklist browser",
      title: "Choose mandal and village",
      description: "Browse warnings by location.",
      mandal: "Mandal",
      village: "Village",
      select: "Select value",
      confirmedTitle: "Confirmed defaulters in the selected area",
    },
    status: {
      workspaceLabel: "Add farmer status",
      title: "Create GREEN, YELLOW, or RED",
      description: "General reputation record for the farmer.",
      note:
        "PAN is not required here; use Aadhaar, mobile, mandal, and village.",
      fields: [
        "Farmer name",
        "Aadhaar number",
        "Mobile number",
        "Mandal",
        "Village",
        "Ration card / address",
      ],
      statusLabel: "Status",
      rulesTitle: "Status rules",
      rules: [
        "Stores a status record for the farmer.",
        "Other dealers can vote once to confirm the pattern.",
        "Admin can remove false or disputed records.",
        "Blacklist stays stronger and separate from the status color.",
      ],
    },
    addBlacklist: {
      workspaceLabel: "Add to blacklist",
      title: "Create a confirmed non-payment warning",
      description:
        "Highest-risk action in the system. It should stay separate from the status record and be shown prominently in search.",
      fields: ["Farmer name", "Aadhaar number", "Mandal", "Village", "Reason", "Address"],
      button: "Add blacklist entry",
      rulesTitle: "Blacklist rules",
      rules: [
        "Blacklist is for confirmed unpaid dues.",
        "It should still appear even if the farmer is GREEN overall.",
        "Only admin can remove a blacklist entry.",
        "Dealers must not confuse it with the general status color.",
      ],
    },
    records: {
      workspaceLabel: "My records",
      title: "See what the logged-in dealer has added",
      description:
        "This section helps the dealer review their own submitted records and keep track of edits and votes.",
      columns: ["Farmer", "Status", "Votes", "Last updated"],
    },
    profile: {
      workspaceLabel: "Profile / Settings",
      title: "Dealer profile and settings",
      description: "Dealer profile, language, authentication, data access, and privacy controls.",
      fields: ["Dealer name", "Shop name", "Mobile number", "District", "Mandal", "Village"],
      settingsTitle: "Document settings",
      language: "Language",
      auth: "Authentication",
      access: "Data access",
      privacy: "Privacy",
      languageValue: "English default. Telugu supported.",
      authValue: "Mobile number + OTP after approval.",
      accessValue: "Only registered and admin-approved dealers can view records.",
      privacyValue: "Aadhaar must never be shown in full; only masked display in the UI.",
    },
    auth: {
      workspaceLabel: "Dealer access",
      loginTitle: "Login to open the dashboard",
      loginSubtitle:
        "Approved dealers sign in here. New dealers should register first and wait for admin approval.",
      mobile: "Mobile number",
      otp: "OTP",
      loginButton: "Login and open dashboard",
      newDealer: "New dealer?",
      registerHint: "Register and wait for admin approval.",
      registerButton: "Register",
      registerTitle: "Register a new dealer",
      registerSubtitle:
        "Fill the form and send the request. Admin will approve the dealer before login is allowed.",
      shop: "Shop name",
      owner: "Owner name",
      district: "District",
      mandal: "Mandal",
      village: "Village",
      aadhaarOrGst: "Aadhaar or GST number",
      aadhaarOrGstPlaceholder: "Enter Aadhaar or GST number",
      submit: "Submit registration",
      pendingTitle: "Registration sent",
      pendingText: "Your dealer request is now pending. Admin must approve it before login.",
      alreadyRegistered: "Already registered?",
      returnLogin: "Return to login.",
    },
    sidebar: {
      todayStats: [
        ["Pending approvals", "18"],
        ["Blacklist lookups", "1,246"],
        ["New records", "93"],
      ],
    },
  },
  te: {
    app: {
      title: "మీ రైతు సమాచారం తెలుసుకోండి",
      workspace: "KYFI డీలర్ వర్క్‌స్పేస్",
      currentSection: "ప్రస్తుత విభాగం",
      menu: "మెనూ",
      selectSection: "ఒక విభాగాన్ని ఎంచుకోండి",
      today: "ఈరోజు",
    },
    common: {
      whatToDoNext: "తర్వాత ఏం చేయాలి",
      whatThisDoes: "ఇది ఏమి చేస్తుంది",
      rules: "నియమాలు",
      searchResult: "శోధన ఫలితం",
      confirmedList: "నిర్ధారిత జాబితా",
    },
    nav: {
      dashboard: { label: "డ్యాష్‌బోర్డ్", note: "సారాంశం" },
      search: { label: "రైతు స్థితి శోధన", note: "వెతకండి" },
      blacklist: { label: "బ్లాక్‌లిస్ట్ బ్రౌజర్", note: "హెచ్చరికలు" },
      status: { label: "రైతు స్థితి జోడించండి", note: "GREEN / YELLOW / RED" },
      addBlacklist: { label: "బ్లాక్‌లిస్ట్‌కి జోడించండి", note: "ముఖ్యం" },
      records: { label: "నా రికార్డులు", note: "చరిత్ర" },
      profile: { label: "ప్రొఫైల్ / సెట్టింగ్స్", note: "ఖాతా" },
    },
    dashboard: {
      title: "హోమ్ / డ్యాష్‌బోర్డ్",
      description: "ఇది ప్రధాన ప్రవేశ స్క్రీన్. Search Farmer Status లేదా View Blacklist కి వెళ్లండి.",
      workspaceLabel: "డీలర్ వర్క్‌స్పేస్",
      searchCardTitle: "రైతు స్థితి శోధన",
      searchCardText: "క్రెడిట్ ఇచ్చే ముందు రైతును శోధించి స్థితి రికార్డును చూడండి.",
      blacklistCardTitle: "బ్లాక్‌లిస్ట్ చూడండి",
      blacklistCardText: "మండలం మరియు గ్రామం ఆధారంగా నిర్ధారిత బాకీలను చూడండి.",
      nextTitle: "తర్వాత ఏం చేయాలి",
      nextText: "లుకప్ కోసం Search Farmer Status తెరవండి, లేదా స్థానిక హెచ్చరికల కోసం View Blacklist తెరవండి.",
      warningTitle: "బ్లాక్‌లిస్ట్ హెచ్చరిక",
      warningText: "BLACKLISTED హెచ్చరిక స్థితి రంగు నుండి వేరుగా ఉంటుంది.",
      warningReady: "View Blacklist సిద్ధం",
      reasonLabel: "కారణం",
      reasonText: "ఋణం తీసుకుని ఒప్పుకున్న కాలంలో తిరిగి చెల్లించలేదు.",
    },
    search: {
      workspaceLabel: "రైతు శోధన",
      title: "గుర్తింపు లేదా గ్రామం ఆధారంగా శోధించండి",
      description: "ఇది ప్రధాన డీలర్ చర్య. కౌంటర్ వద్ద వేగంగా ఉపయోగించడానికి రూపొందించబడింది.",
      primary: "Aadhaar / PAN / Mobile",
      mandal: "మండలం",
      village: "గ్రామం",
      enter: "విలువ నమోదు చేయండి",
      button: "రైతును శోధించండి",
      resultTitle: "రమా దేవి",
      resultLocation: "గుంటూరు తూర్పు, కొండపల్లి",
      blacklisted: "బ్లాక్‌లిస్ట్‌లో ఉంది",
      warning:
        "నిర్ధారిత చెల్లింపు చేయని హెచ్చరిక ఉంది. ఏ క్రెడిట్ నిర్ణయానికి ముందే ఇది చూపించాలి.",
      aadhaar: "Aadhaar",
      mobile: "Mobile",
      votes: "ఓట్ల సంఖ్య",
      date: "జోడించిన తేదీ",
    },
    blacklist: {
      workspaceLabel: "బ్లాక్‌లిస్ట్ బ్రౌజర్",
      title: "మండలం మరియు గ్రామాన్ని ఎంచుకోండి",
      description: "స్థానం ఆధారంగా హెచ్చరికలను చూడండి.",
      mandal: "మండలం",
      village: "గ్రామం",
      select: "విలువను ఎంచుకోండి",
      confirmedTitle: "ఎంచుకున్న ప్రాంతంలో నిర్ధారిత బాకీలు",
    },
    status: {
      workspaceLabel: "రైతు స్థితి జోడించండి",
      title: "GREEN, YELLOW, లేదా RED సృష్టించండి",
      description: "రైతు యొక్క సాధారణ విశ్వసనీయత రికార్డు.",
      note:
        "ఇక్కడ PAN అవసరం లేదు; Aadhaar, mobile, mandal, మరియు village ఉపయోగించండి.",
      fields: ["రైతు పేరు", "Aadhaar సంఖ్య", "మొబైల్ నంబర్", "మండలం", "గ్రామం", "రేషన్ కార్డ్ / చిరునామా"],
      statusLabel: "స్థితి",
      rulesTitle: "స్థితి నియమాలు",
      rules: [
        "రైతు కోసం స్థితి రికార్డు నిల్వ చేస్తుంది.",
        "ఇతర డీలర్లు ఒకసారి ఓటు వేసి ధృవీకరించగలరు.",
        "తప్పుడు లేదా వివాదాస్పద రికార్డులను అడ్మిన్ తొలగించగలరు.",
        "బ్లాక్‌లిస్ట్ స్థితి రంగు కన్నా ఎక్కువ ప్రాధాన్యం కలిగి ఉంటుంది.",
      ],
    },
    addBlacklist: {
      workspaceLabel: "బ్లాక్‌లిస్ట్‌కు జోడించండి",
      title: "నిర్ధారిత చెల్లించని హెచ్చరిక సృష్టించండి",
      description:
        "ఇది వ్యవస్థలో అత్యంత కీలక చర్య. ఇది స్థితి రికార్డు నుండి వేరుగా ఉండాలి మరియు శోధనలో స్పష్టంగా కనిపించాలి.",
      fields: ["రైతు పేరు", "Aadhaar సంఖ్య", "మండలం", "గ్రామం", "కారణం", "చిరునామా"],
      button: "బ్లాక్‌లిస్ట్ ఎంట్రీ జోడించండి",
      rulesTitle: "బ్లాక్‌లిస్ట్ నియమాలు",
      rules: [
        "బ్లాక్‌లిస్ట్ నిర్ధారిత చెల్లించని బాకీల కోసం మాత్రమే.",
        "రైతు మొత్తం GREEN అయినా ఇది చూపించాలి.",
        "బ్లాక్‌లిస్ట్ ఎంట్రీని అడ్మిన్ మాత్రమే తొలగించగలరు.",
        "ఇది సాధారణ స్థితి రంగుతో కలపకూడదు.",
      ],
    },
    records: {
      workspaceLabel: "నా రికార్డులు",
      title: "లాగిన్ అయిన డీలర్ జోడించినవి చూడండి",
      description:
        "ఈ విభాగం డీలర్ తన సమర్పించిన రికార్డులను సమీక్షించడానికి మరియు ఎడిట్‌లు, ఓట్లను ట్రాక్ చేయడానికి ఉపయోగపడుతుంది.",
      columns: ["రైతు", "స్థితి", "ఓట్లు", "చివరి నవీకరణ"],
    },
    profile: {
      workspaceLabel: "ప్రొఫైల్ / సెట్టింగ్స్",
      title: "డీలర్ ప్రొఫైల్ మరియు సెట్టింగ్స్",
      description: "డీలర్ ప్రొఫైల్, భాష, ప్రామాణీకరణ, డేటా యాక్సెస్, మరియు గోప్యత నియంత్రణలు.",
      fields: ["డీలర్ పేరు", "షాప్ పేరు", "మొబైల్ నంబర్", "జిల్లా", "మండలం", "గ్రామం"],
      settingsTitle: "డాక్యుమెంట్ సెట్టింగ్స్",
      language: "భాష",
      auth: "ప్రామాణీకరణ",
      access: "డేటా యాక్సెస్",
      privacy: "గోప్యత",
      languageValue: "ఇంగ్లీష్ డిఫాల్ట్. తెలుగు సపోర్ట్ ఉంది.",
      authValue: "అప్రూవల్ తర్వాత మొబైల్ నంబర్ + OTP.",
      accessValue: "రిజిస్టర్ అయ్యి అడ్మిన్ ఆమోదించిన డీలర్లు మాత్రమే రికార్డులు చూడగలరు.",
      privacyValue: "Aadhaar పూర్తి రూపంలో చూపించకూడదు; UIలో masked గా మాత్రమే చూపాలి.",
    },
    auth: {
      workspaceLabel: "డీలర్ యాక్సెస్",
      loginTitle: "డ్యాష్‌బోర్డ్ తెరవడానికి లాగిన్ చేయండి",
      loginSubtitle:
        "ఆమోదించిన డీలర్లు ఇక్కడ లాగిన్ అవుతారు. కొత్త డీలర్లు ముందుగా రిజిస్టర్ అయి అడ్మిన్ ఆమోదం కోసం వేచి ఉండాలి.",
      mobile: "మొబైల్ నంబర్",
      otp: "OTP",
      loginButton: "లాగిన్ చేసి డ్యాష్‌బోర్డ్ తెరవండి",
      newDealer: "కొత్త డీలరా?",
      registerHint: "రిజిస్టర్ అయి అడ్మిన్ ఆమోదం కోసం వేచి ఉండండి.",
      registerButton: "రిజిస్టర్",
      registerTitle: "కొత్త డీలర్‌ను రిజిస్టర్ చేయండి",
      registerSubtitle:
        "ఫారమ్ నింపి అభ్యర్థన పంపండి. లాగిన్‌కు ముందు అడ్మిన్ ఆమోదిస్తారు.",
      shop: "షాప్ పేరు",
      owner: "యజమాని పేరు",
      district: "జిల్లా",
      mandal: "మండలం",
      village: "గ్రామం",
      aadhaarOrGst: "Aadhaar లేదా GST సంఖ్య",
      aadhaarOrGstPlaceholder: "Aadhaar లేదా GST సంఖ్యను నమోదు చేయండి",
      submit: "రిజిస్ట్రేషన్ పంపండి",
      pendingTitle: "రిజిస్ట్రేషన్ పంపబడింది",
      pendingText: "మీ డీలర్ అభ్యర్థన పెండింగ్‌లో ఉంది. లాగిన్‌కు ముందు అడ్మిన్ ఆమోదించాలి.",
      alreadyRegistered: "ఇప్పటికే రిజిస్టర్ అయ్యారా?",
      returnLogin: "లాగిన్‌కు తిరిగి వెళ్లండి.",
    },
    sidebar: {
      todayStats: [
        ["పెండింగ్ ఆమోదాలు", "18"],
        ["బ్లాక్‌లిస్ట్ శోధనలు", "1,246"],
        ["కొత్త రికార్డులు", "93"],
      ],
    },
  },
} satisfies Record<KyfiLocale, unknown>;
